controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: home
  - group: gripper
    pose: close