# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - end_effector_controller
    - owl_arm_controller

  end_effector_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - W3J
    action_ns: follow_joint_trajectory
    default: true
  owl_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
    action_ns: follow_joint_trajectory
    default: true